const countries = {
    "am-ET": "Amharic",
    "ar-SA": "Arabic",
    "bn-BD": "Bengali",
    "zh-CN": "Chinese (Mandarin)",
    "zh-TW": "Chinese (Taiwan)",
    "cs-CZ": "Czech",
    "da-DK": "Danish",
    "nl-NL": "Dutch",
    "en-US": "English (United States)",
    "en-GB": "English (United Kingdom)",
    "fi-FI": "Finnish",
    "fr-FR": "French",
    "de-DE": "German",
    "el-GR": "Greek",
    "gu-IN": "Gujarati",
    "he-IL": "Hebrew",
    "hi-IN": "Hindi",
    "hu-HU": "Hungarian",
    "is-IS": "Icelandic",
    "id-ID": "Indonesian",
    "it-IT": "Italian",
    "ja-JP": "Japanese",
    "kn-IN": "Kannada",
    "ko-KR": "Korean",
    "lv-LV": "Latvian",
    "lt-LT": "Lithuanian",
    "ml-IN": "Malayalam",
    "mr-IN": "Marathi",
    "nb-NO": "Norwegian",
    "pa-IN": "Punjabi",
    "pl-PL": "Polish",
    "pt-PT": "Portuguese",
    "pt-BR": "Portuguese (Brazil)",
    "ro-RO": "Romanian",
    "ru-RU": "Russian",
    "sr-RS": "Serbian",
    "sk-SK": "Slovak",
    "sl-SI": "Slovenian",
    "es-ES": "Spanish (Spain)",
    "es-MX": "Spanish (Mexico)",
    "sv-SE": "Swedish",
    "ta-IN": "Tamil",
    "te-IN": "Telugu",
    "th-TH": "Thai",
    "tr-TR": "Turkish",
    "uk-UA": "Ukrainian",
    "ur-PK": "Urdu",
    "vi-VN": "Vietnamese",
    "zu-ZA": "Zulu"
  };
  
//   console.log(languages);
  